global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'microservices'
    static_configs:
      - targets: 
        - 'user-service:8000'
        - 'product-service:8000'
        - 'order-service:8000'
        - 'inventory-service:8000'
        - 'payment-service:8000'
